version: '3.1'
services:
  app:
    container_name: springboot-weather-postgresql
    image: springboot-weather-postgresql
    build: ./
    ports:
      - "80:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb